// Code generated by "so test". DO NOT EDIT.

package main

import (
	"solod.dev/so/os"
	"solod.dev/so/testing"
)

func main() {
	testing.RunTests("so/sync/atomic", os.Args, []testing.Test{
		{Name: "TestBool", F: TestBool},
		{Name: "TestInt32_Concurrent", F: TestInt32_Concurrent},
		{Name: "TestInt32_SwapCAS", F: TestInt32_SwapCAS},
		{Name: "TestInt64_Concurrent", F: TestInt64_Concurrent},
		{Name: "TestInt64_SwapCAS", F: TestInt64_SwapCAS},
		{Name: "TestPointer", F: TestPointer},
		{Name: "TestUint32", F: TestUint32},
		{Name: "TestUint64", F: TestUint64},
	})
}
