// Code generated by "so test". DO NOT EDIT.

package main

import (
	"solod.dev/so/os"
	"solod.dev/so/testing"
)

func main() {
	testing.RunTests("so/maps", os.Args, []testing.Test{
		{Name: "TestIter", F: TestIter},
		{Name: "TestIter_Empty", F: TestIter_Empty},
		{Name: "TestSetGet", F: TestSetGet},
		{Name: "TestStringValues", F: TestStringValues},
		{Name: "TestHas", F: TestHas},
		{Name: "TestDelete", F: TestDelete},
		{Name: "TestOverwrite", F: TestOverwrite},
		{Name: "TestMissing", F: TestMissing},
		{Name: "TestGrow", F: TestGrow},
		{Name: "TestReturnMap", F: TestReturnMap},
	})
}
