// Code generated by "so test". DO NOT EDIT.

package main

import (
	"solod.dev/so/os"
	"solod.dev/so/testing"
)

func main() {
	testing.RunTests("so/bufio", os.Args, []testing.Test{
		{Name: "TestReader_ReadString", F: TestReader_ReadString},
		{Name: "TestReader_ReadByte", F: TestReader_ReadByte},
		{Name: "TestReader_Peek", F: TestReader_Peek},
		{Name: "TestScanner", F: TestScanner},
		{Name: "TestWriter_WriteRune", F: TestWriter_WriteRune},
	})
}
