// Code generated by "so test". DO NOT EDIT.

package main

import (
	"solod.dev/so/os"
	"solod.dev/so/testing"
)

func main() {
	testing.RunTests("so/strings", os.Args, []testing.Test{
		{Name: "TestClone", F: TestClone},
		{Name: "TestCompare", F: TestCompare},
		{Name: "TestCount", F: TestCount},
		{Name: "TestCut", F: TestCut},
		{Name: "TestCutPrefixSuffix", F: TestCutPrefixSuffix},
		{Name: "TestIndex", F: TestIndex},
		{Name: "TestHasPrefixSuffix", F: TestHasPrefixSuffix},
		{Name: "TestTrimPrefixSuffix", F: TestTrimPrefixSuffix},
		{Name: "TestRepeat", F: TestRepeat},
		{Name: "TestReplace", F: TestReplace},
		{Name: "TestSplitJoin", F: TestSplitJoin},
		{Name: "TestToUpperLower", F: TestToUpperLower},
		{Name: "TestTrim", F: TestTrim},
		{Name: "TestBuilder", F: TestBuilder},
		{Name: "TestReader", F: TestReader},
	})
}
