// Code generated by "so test". DO NOT EDIT.

package main

import (
	"solod.dev/so/os"
	"solod.dev/so/testing"
)

func main() {
	testing.RunTests("so/bytes", os.Args, []testing.Test{
		{Name: "TestBuffer_Stack", F: TestBuffer_Stack},
		{Name: "TestBuffer_Heap", F: TestBuffer_Heap},
		{Name: "TestClone", F: TestClone},
		{Name: "TestCompare", F: TestCompare},
		{Name: "TestEqual", F: TestEqual},
		{Name: "TestContains", F: TestContains},
		{Name: "TestCount", F: TestCount},
		{Name: "TestCut", F: TestCut},
		{Name: "TestHasPrefix", F: TestHasPrefix},
		{Name: "TestHasSuffix", F: TestHasSuffix},
		{Name: "TestIndex", F: TestIndex},
		{Name: "TestJoin", F: TestJoin},
		{Name: "TestMap", F: TestMap},
		{Name: "TestRepeat", F: TestRepeat},
		{Name: "TestReplace", F: TestReplace},
		{Name: "TestRunes", F: TestRunes},
		{Name: "TestSplit", F: TestSplit},
		{Name: "TestTrim", F: TestTrim},
		{Name: "TestTrimPrefix", F: TestTrimPrefix},
		{Name: "TestToLower", F: TestToLower},
		{Name: "TestToUpper", F: TestToUpper},
		{Name: "TestReader_Read", F: TestReader_Read},
	})
}
