// Code generated by "so test". DO NOT EDIT.

package main

import (
	"solod.dev/so/os"
	"solod.dev/so/testing"
)

func main() {
	testing.RunTests("so/cmp", os.Args, []testing.Test{
		{Name: "TestCompare", F: TestCompare},
		{Name: "TestEqual", F: TestEqual},
		{Name: "TestLess", F: TestLess},
	})
}
