// Code generated by "so test". DO NOT EDIT.

package main

import (
	"solod.dev/so/os"
	"solod.dev/so/testing"
)

func main() {
	testing.RunTests("so/mem", os.Args, []testing.Test{
		{Name: "TestTryAlloc", F: TestTryAlloc},
		{Name: "TestTryAllocSlice", F: TestTryAllocSlice},
		{Name: "TestAlloc", F: TestAlloc},
		{Name: "TestAllocDefault", F: TestAllocDefault},
		{Name: "TestAllocSlice", F: TestAllocSlice},
		{Name: "TestAllocSliceDefault", F: TestAllocSliceDefault},
		{Name: "TestTryReallocSlice", F: TestTryReallocSlice},
		{Name: "TestReallocSlice", F: TestReallocSlice},
		{Name: "TestReallocSlice_Empty", F: TestReallocSlice_Empty},
		{Name: "TestFreeNil", F: TestFreeNil},
		{Name: "TestFreeString", F: TestFreeString},
		{Name: "TestTracker", F: TestTracker},
		{Name: "TestArena", F: TestArena},
		{Name: "TestArray", F: TestArray},
	})
}
