// Code generated by "so test". DO NOT EDIT.

package main

import (
	"solod.dev/so/os"
	"solod.dev/so/testing"
)

func main() {
	testing.RunTests("so/strconv", os.Args, []testing.Test{
		{Name: "TestAppendBool", F: TestAppendBool},
		{Name: "TestAppendFloat", F: TestAppendFloat},
		{Name: "TestAppendInt", F: TestAppendInt},
		{Name: "TestAppendUint", F: TestAppendUint},
		{Name: "TestAtof", F: TestAtof},
		{Name: "TestAtoi", F: TestAtoi},
		{Name: "TestFormatBool", F: TestFormatBool},
		{Name: "TestFormatFloat", F: TestFormatFloat},
		{Name: "TestFormatInt", F: TestFormatInt},
		{Name: "TestFormatUint", F: TestFormatUint},
		{Name: "TestItoa", F: TestItoa},
		{Name: "TestParseBool", F: TestParseBool},
		{Name: "TestParseFloat", F: TestParseFloat},
		{Name: "TestParseInt", F: TestParseInt},
		{Name: "TestParseUint", F: TestParseUint},
	})
}
