// Code generated by "so test". DO NOT EDIT.

package main

import "solod.dev/so/testing"

func main() {
	testing.RunTests("so/time", []testing.Test{
		{Name: "TestFormat_RFC3339", F: TestFormat_RFC3339},
		{Name: "TestFormat_RFC3339Nano", F: TestFormat_RFC3339Nano},
		{Name: "TestFormat_DateTime", F: TestFormat_DateTime},
		{Name: "TestFormat_DateOnly", F: TestFormat_DateOnly},
		{Name: "TestFormat_TimeOnly", F: TestFormat_TimeOnly},
		{Name: "TestFormat_Custom", F: TestFormat_Custom},
		{Name: "TestString", F: TestString},
		{Name: "TestParse_RFC3339", F: TestParse_RFC3339},
		{Name: "TestParse_RFC3339Nano", F: TestParse_RFC3339Nano},
		{Name: "TestParse_RFC3339PosOffset", F: TestParse_RFC3339PosOffset},
		{Name: "TestParse_RFC3339NegOffset", F: TestParse_RFC3339NegOffset},
		{Name: "TestParse_RFC3339NanoOffset", F: TestParse_RFC3339NanoOffset},
		{Name: "TestParse_DateTime", F: TestParse_DateTime},
		{Name: "TestParse_DateTimeOffset", F: TestParse_DateTimeOffset},
		{Name: "TestParse_DateOnly", F: TestParse_DateOnly},
		{Name: "TestParse_TimeOnly", F: TestParse_TimeOnly},
		{Name: "TestParse_Custom", F: TestParse_Custom},
		{Name: "TestParse_Error", F: TestParse_Error},
		{Name: "TestDate", F: TestDate},
		{Name: "TestNow", F: TestNow},
		{Name: "TestSleep", F: TestSleep},
		{Name: "TestSleepNonPositive", F: TestSleepNonPositive},
	})
}
