// Code generated by "so test". DO NOT EDIT.

package main

import (
	"solod.dev/so/os"
	"solod.dev/so/testing"
)

func main() {
	testing.RunTests("so/math", os.Args, []testing.Test{
		{Name: "TestAbs", F: TestAbs},
		{Name: "TestAcos", F: TestAcos},
		{Name: "TestAcosh", F: TestAcosh},
		{Name: "TestAsin", F: TestAsin},
		{Name: "TestAsinh", F: TestAsinh},
		{Name: "TestAtan", F: TestAtan},
		{Name: "TestAtan2", F: TestAtan2},
		{Name: "TestAtanh", F: TestAtanh},
		{Name: "TestCbrt", F: TestCbrt},
		{Name: "TestCeil", F: TestCeil},
		{Name: "TestCopysign", F: TestCopysign},
		{Name: "TestCos", F: TestCos},
		{Name: "TestCosh", F: TestCosh},
		{Name: "TestDim", F: TestDim},
		{Name: "TestExp", F: TestExp},
		{Name: "TestExp2", F: TestExp2},
		{Name: "TestExpm1", F: TestExpm1},
		{Name: "TestFloor", F: TestFloor},
		{Name: "TestLog", F: TestLog},
		{Name: "TestLog2", F: TestLog2},
		{Name: "TestLog10", F: TestLog10},
		{Name: "TestMod", F: TestMod},
		{Name: "TestModf", F: TestModf},
		{Name: "TestPow", F: TestPow},
		{Name: "TestPow10", F: TestPow10},
		{Name: "TestRemainder", F: TestRemainder},
		{Name: "TestRound", F: TestRound},
		{Name: "TestRoundToEven", F: TestRoundToEven},
		{Name: "TestSin", F: TestSin},
		{Name: "TestSinh", F: TestSinh},
		{Name: "TestSqrt", F: TestSqrt},
		{Name: "TestTan", F: TestTan},
		{Name: "TestTanh", F: TestTanh},
		{Name: "TestTrunc", F: TestTrunc},
	})
}
