// Code generated by "so test". DO NOT EDIT.

package main

import (
	"solod.dev/so/os"
	"solod.dev/so/testing"
)

func main() {
	testing.RunTests("so/c", os.Args, []testing.Test{
		{Name: "TestAssert", F: TestAssert},
		{Name: "TestString", F: TestString},
		{Name: "TestExtern", F: TestExtern},
		{Name: "TestVal", F: TestVal},
		{Name: "TestRaw", F: TestRaw},
		{Name: "TestCString", F: TestCString},
		{Name: "TestNumericTypes", F: TestNumericTypes},
	})
}
