// Code generated by "so test". DO NOT EDIT.

package main

import (
	"solod.dev/so/os"
	"solod.dev/so/testing"
)

func main() {
	testing.RunTests("so/net/netip", os.Args, []testing.Test{
		{Name: "TestParseAddr_IPv4", F: TestParseAddr_IPv4},
		{Name: "TestParseAddr_IPv6", F: TestParseAddr_IPv6},
		{Name: "TestAddr_String", F: TestAddr_String},
		{Name: "TestAddr_Is", F: TestAddr_Is},
		{Name: "TestAddr_Props", F: TestAddr_Props},
		{Name: "TestAddr_Compare", F: TestAddr_Compare},
		{Name: "TestAddr_NextPrev", F: TestAddr_NextPrev},
		{Name: "TestAddr_Unmap", F: TestAddr_Unmap},
		{Name: "TestAddrFrom", F: TestAddrFrom},
		{Name: "TestAddrPort_IPv4", F: TestAddrPort_IPv4},
		{Name: "TestAddrPort_IPv6", F: TestAddrPort_IPv6},
		{Name: "TestPrefix", F: TestPrefix},
		{Name: "TestPrefix_Masked", F: TestPrefix_Masked},
		{Name: "TestPrefix_Overlaps", F: TestPrefix_Overlaps},
	})
}
