// Code generated by "so test". DO NOT EDIT.

package main

import (
	"solod.dev/so/os"
	"solod.dev/so/testing"
)

func main() {
	testing.RunTests("so/slices", os.Args, []testing.Test{
		{Name: "TestMake", F: TestMake},
		{Name: "TestAppend", F: TestAppend},
		{Name: "TestAppend_Grow", F: TestAppend_Grow},
		{Name: "TestAppend_Nil", F: TestAppend_Nil},
		{Name: "TestExtend", F: TestExtend},
		{Name: "TestExtend_Nil", F: TestExtend_Nil},
		{Name: "TestClone", F: TestClone},
		{Name: "TestEqual", F: TestEqual},
		{Name: "TestEqual_Strings", F: TestEqual_Strings},
		{Name: "TestEqual_Structs", F: TestEqual_Structs},
		{Name: "TestIndex", F: TestIndex},
		{Name: "TestContains", F: TestContains},
		{Name: "TestMinMax_Ints", F: TestMinMax_Ints},
		{Name: "TestMinMax_Strings", F: TestMinMax_Strings},
		{Name: "TestIsSorted", F: TestIsSorted},
		{Name: "TestIsSortedFunc", F: TestIsSortedFunc},
		{Name: "TestSort_Ints", F: TestSort_Ints},
		{Name: "TestSort_Float64s", F: TestSort_Float64s},
		{Name: "TestSort_Strings", F: TestSort_Strings},
		{Name: "TestSortFunc", F: TestSortFunc},
		{Name: "TestSortFunc_Nil", F: TestSortFunc_Nil},
		{Name: "TestSortStableFunc_Ints", F: TestSortStableFunc_Ints},
		{Name: "TestSortStableFunc_Float64s", F: TestSortStableFunc_Float64s},
		{Name: "TestSortStableFunc_Strings", F: TestSortStableFunc_Strings},
	})
}
