// Code generated by "so test". DO NOT EDIT.

package main

import (
	"solod.dev/so/os"
	"solod.dev/so/testing"
)

func main() {
	testing.RunTests("so/crypto/crand", os.Args, []testing.Test{
		{Name: "TestRead", F: TestRead},
		{Name: "TestRead_Empty", F: TestRead_Empty},
		{Name: "TestReader", F: TestReader},
		{Name: "TestText", F: TestText},
	})
}
