// Code generated by "so test". DO NOT EDIT.

package main

import (
	"solod.dev/so/os"
	"solod.dev/so/testing"
)

func main() {
	testing.RunTests("so/encoding/binary", os.Args, []testing.Test{
		{Name: "TestBigEndian", F: TestBigEndian},
		{Name: "TestLittleEndian", F: TestLittleEndian},
	})
}
