// Code generated by "so test". DO NOT EDIT.

package main

import (
	"solod.dev/so/os"
	"solod.dev/so/testing"
)

func main() {
	testing.RunTests("so/bytealg", os.Args, []testing.Test{
		{Name: "TestCompare", F: TestCompare},
		{Name: "TestCount", F: TestCount},
		{Name: "TestEqual", F: TestEqual},
		{Name: "TestIndexRabinKarp", F: TestIndexRabinKarp},
		{Name: "TestLastIndexRabinKarp", F: TestLastIndexRabinKarp},
		{Name: "TestIndexByte", F: TestIndexByte},
		{Name: "TestLastIndexByte", F: TestLastIndexByte},
	})
}
