// Code generated by "so test". DO NOT EDIT.

package main

import (
	"solod.dev/so/os"
	"solod.dev/so/testing"
)

func main() {
	testing.RunTests("so/path", os.Args, []testing.Test{
		{Name: "TestClean", F: TestClean},
		{Name: "TestSplit", F: TestSplit},
		{Name: "TestJoin", F: TestJoin},
		{Name: "TestIsAbs", F: TestIsAbs},
		{Name: "TestDir", F: TestDir},
		{Name: "TestBase", F: TestBase},
		{Name: "TestExt", F: TestExt},
		{Name: "TestMatch", F: TestMatch},
	})
}
