// Code generated by "so test". DO NOT EDIT.

package main

import (
	"solod.dev/so/os"
	"solod.dev/so/testing"
)

func main() {
	testing.RunTests("so/runtime", os.Args, []testing.Test{
		{Name: "TestGOOS", F: TestGOOS},
		{Name: "TestGOARCH", F: TestGOARCH},
		{Name: "TestFileName", F: TestFileName},
		{Name: "TestLine", F: TestLine},
		{Name: "TestFuncName", F: TestFuncName},
		{Name: "TestNumCPU", F: TestNumCPU},
		{Name: "TestVersion", F: TestVersion},
	})
}
