// Code generated by "so test". DO NOT EDIT.

package main

import (
	"solod.dev/so/os"
	"solod.dev/so/testing"
)

func main() {
	testing.RunTests("so/runtime", os.Args, []testing.Test{
		{Name: "TestVersion", F: TestVersion},
		{Name: "TestGOOS", F: TestGOOS},
		{Name: "TestGOARCH", F: TestGOARCH},
	})
}
