// Code generated by "so test". DO NOT EDIT.

package main

import (
	"solod.dev/so/os"
	"solod.dev/so/testing"
)

func main() {
	testing.RunTests("so/unicode/utf8", os.Args, []testing.Test{
		{Name: "TestDecodeLastRune", F: TestDecodeLastRune},
		{Name: "TestDecodeLastRuneInString", F: TestDecodeLastRuneInString},
		{Name: "TestDecodeRune", F: TestDecodeRune},
		{Name: "TestDecodeRuneInString", F: TestDecodeRuneInString},
		{Name: "TestEncodeRune", F: TestEncodeRune},
		{Name: "TestRuneCount", F: TestRuneCount},
		{Name: "TestRuneCountInString", F: TestRuneCountInString},
		{Name: "TestRuneLen", F: TestRuneLen},
		{Name: "TestValidString", F: TestValidString},
		{Name: "TestAppendRune", F: TestAppendRune},
	})
}
