// Code generated by "so test". DO NOT EDIT.

package main

import (
	"solod.dev/so/os"
	"solod.dev/so/testing"
)

func main() {
	testing.RunTests("so/encoding/hex", os.Args, []testing.Test{
		{Name: "TestEncode", F: TestEncode},
		{Name: "TestEncodeToString", F: TestEncodeToString},
		{Name: "TestDecode", F: TestDecode},
		{Name: "TestDecodeString", F: TestDecodeString},
		{Name: "TestDump", F: TestDump},
	})
}
