// Code generated by "so test". DO NOT EDIT.

package main

import (
	"solod.dev/so/os"
	"solod.dev/so/testing"
)

func main() {
	testing.RunTests("so/flag", os.Args, []testing.Test{
		{Name: "TestParse", F: TestParse},
	})
}
