// Code generated by "so test". DO NOT EDIT.

package main

import (
	"solod.dev/so/os"
	"solod.dev/so/testing"
)

func main() {
	testing.RunTests("so/os", os.Args, []testing.Test{
		{Name: "TestArgs", F: TestArgs},
		{Name: "TestWriteReadFile", F: TestWriteReadFile},
		{Name: "TestCreateWriteClose", F: TestCreateWriteClose},
		{Name: "TestOpenReadClose", F: TestOpenReadClose},
		{Name: "TestWriteString", F: TestWriteString},
		{Name: "TestStdoutStderr", F: TestStdoutStderr},
		{Name: "TestReadDir", F: TestReadDir},
		{Name: "TestReadDir_NotExist", F: TestReadDir_NotExist},
		{Name: "TestSetGetenv", F: TestSetGetenv},
		{Name: "TestLookupEnv_Present", F: TestLookupEnv_Present},
		{Name: "TestLookupEnv_Absent", F: TestLookupEnv_Absent},
		{Name: "TestUnsetenv", F: TestUnsetenv},
		{Name: "TestGetenv_PATH", F: TestGetenv_PATH},
		{Name: "TestOpenFile_Create", F: TestOpenFile_Create},
		{Name: "TestOpenFile_RdOnly", F: TestOpenFile_RdOnly},
		{Name: "TestFile_Name", F: TestFile_Name},
		{Name: "TestLink", F: TestLink},
		{Name: "TestSymlink", F: TestSymlink},
		{Name: "TestMkdirChdir", F: TestMkdirChdir},
		{Name: "TestTruncate", F: TestTruncate},
		{Name: "TestOpenFile_Append", F: TestOpenFile_Append},
		{Name: "TestChtimes", F: TestChtimes},
		{Name: "TestChown", F: TestChown},
		{Name: "TestLchown", F: TestLchown},
		{Name: "TestRemove", F: TestRemove},
		{Name: "TestRename", F: TestRename},
		{Name: "TestMkdir_ErrExist", F: TestMkdir_ErrExist},
		{Name: "TestOpen_ErrNotExist", F: TestOpen_ErrNotExist},
		{Name: "TestOpenFile_ErrNotExist", F: TestOpenFile_ErrNotExist},
		{Name: "TestGetpid", F: TestGetpid},
		{Name: "TestGetppid", F: TestGetppid},
		{Name: "TestGetuid", F: TestGetuid},
		{Name: "TestGeteuid", F: TestGeteuid},
		{Name: "TestGetgid", F: TestGetgid},
		{Name: "TestGetegid", F: TestGetegid},
		{Name: "TestGetwd", F: TestGetwd},
		{Name: "TestHostname", F: TestHostname},
		{Name: "TestSeek", F: TestSeek},
		{Name: "TestReadAt", F: TestReadAt},
		{Name: "TestWriteAt", F: TestWriteAt},
		{Name: "TestStat_File", F: TestStat_File},
		{Name: "TestStat_Dir", F: TestStat_Dir},
		{Name: "TestLstat_Symlink", F: TestLstat_Symlink},
		{Name: "TestSameFile", F: TestSameFile},
		{Name: "TestStat_NotExist", F: TestStat_NotExist},
		{Name: "TestChmod", F: TestChmod},
		{Name: "TestTempDir", F: TestTempDir},
		{Name: "TestCreateTemp", F: TestCreateTemp},
		{Name: "TestCreateTemp_Dir", F: TestCreateTemp_Dir},
		{Name: "TestMkdirTemp", F: TestMkdirTemp},
	})
}
